[versions]
activityCompose = "1.12.2"
activityComposeVersion = "1.12.2"
annotation = "1.9.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
converterScalars = "3.0.0"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
filepicker = "1.3.2"
fragment = "1.8.9"
gson = "2.13.2"
hiltAndroid = "2.59"
hiltAndroidCompiler = "2.59"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCoroutinesCore = "1.10.2"
lifecycleViewmodelCompose = "2.10.0"
lottie = "6.7.1"
material = "1.10.1"
compiler = "1.5.15"
material3 = "1.4.0"
materialIconsExtended = "1.7.8"
materialVersion = "1.13.0"
navigationCompose = "2.9.6"
roomKtx = "2.8.4"
supportAnnotations = "28.0.0"
swiperefreshlayout = "1.2.0"
uiTooling = "1.10.1"
compose-bom = "2026.01.00"
android-application = "9.0.0"
kotlin-android = "2.2.10"
google-ksp = "2.3.2"
kotlin-compose = "2.0.20"
dagger-hilt = "2.57.2"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTooling" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationCompose" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationCompose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterScalars" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
dagger = { module = "com.google.dagger:dagger", version.ref = "hiltAndroidCompiler" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hiltAndroidCompiler" }
filepicker = { module = "com.github.jaiselrahman:FilePicker", version.ref = "filepicker" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroid" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterScalars" }
support-annotations = { module = "com.android.support:support-annotations", version.ref = "supportAnnotations" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
android-library = { id = "com.android.library", version.ref = "android-application" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-compose" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
safe-args = { id = "androidx.navigation.safeargs" }
android-dagger-hilt = { id = "dagger.hilt.android.plugin" }